"""Refine v1 pseudo-labels with absolute confidence + per-class calibration.

Inputs:
  - bruce_on_unlabeled.npz (regenerated by build_pseudo_labels.py)
  - labeled per-class AUC table (from model_audit)

Strategy:
  1. Use Bruce absolute probability (sigmoid output) as the primary confidence.
  2. Per-class threshold: scale by Bruce's labeled per-class AUC.
     - Bruce AUC > 0.95 on labeled → threshold 0.85 (trust the model)
     - Bruce AUC 0.85-0.95 → threshold 0.90
     - Bruce AUC 0.70-0.85 → threshold 0.95 (require near-certain)
     - Bruce AUC < 0.70 OR NaN → require BOTH bruce>=0.95 AND perch_soft>=0.5 (consensus)
  3. Cap per-class count adaptively (more for confident classes, fewer for risky).
  4. Augment with hour-prior boost where applicable (the +0.107 lift from prior re-tune).

Output: pseudo_labels_v2.parquet with per-row {label, abs_confidence, calibration_tier}.
"""
import os, re, json
import numpy as np
import pandas as pd
from sklearn.metrics import roc_auc_score

REPO = "/home/user/opencode/birdclef-2026"
OUT = f"{REPO}/analysis/context_label"

# ---------- Load Bruce predictions on unlabeled ----------
print("Loading Bruce predictions on unlabeled...")
data = np.load(f"{OUT}/bruce_on_unlabeled.npz", allow_pickle=True)
P_bruce = data["P_bruce"]  # (127k, 234)
P_perch_soft = data["perch_soft"]  # (127k, 234)
classes = list(data["classes"])
N_PSEUDO, N_CLS = P_bruce.shape
meta = pd.DataFrame({
    "row_id": data["row_id"],
    "filename": data["filename"],
    "site": data["site"],
    "hour": data["hour_utc"].astype(int),
    "year": data["year"].astype(int),
})


# ---------- Load Bruce per-class AUC on labeled ----------
print("Loading Bruce per-class AUC on labeled...")
br_lab = np.load("/tmp/bruce_out/labeled_oof_perch_bruce.npz", allow_pickle=True)
Y = br_lab["Y"]
P_bruce_lab = br_lab["P_bruce"]

bruce_per_class_auc = np.full(N_CLS, np.nan)
n_pos_per_class = np.zeros(N_CLS, dtype=int)
for c in range(N_CLS):
    n_pos = int(Y[:, c].sum())
    n_pos_per_class[c] = n_pos
    if n_pos == 0 or n_pos == len(Y):
        continue
    col = P_bruce_lab[:, c]
    mask = ~np.isnan(col)
    if mask.sum() < 5 or Y[mask, c].sum() == 0 or Y[mask, c].sum() == mask.sum():
        continue
    try:
        bruce_per_class_auc[c] = roc_auc_score(Y[mask, c], col[mask])
    except Exception:
        pass

print(f"  classes with measured Bruce AUC: {(~np.isnan(bruce_per_class_auc)).sum()}/{N_CLS}")
print(f"  Bruce AUC distribution: mean={np.nanmean(bruce_per_class_auc):.3f} "
      f"median={np.nanmedian(bruce_per_class_auc):.3f} "
      f"min={np.nanmin(bruce_per_class_auc):.3f} "
      f"max={np.nanmax(bruce_per_class_auc):.3f}")


# ---------- Per-class threshold tiers ----------
def threshold_for_class(c_idx):
    auc = bruce_per_class_auc[c_idx]
    if np.isnan(auc):
        return ("untested", 0.95, True)  # require Bruce + Perch consensus
    if auc >= 0.95:
        return ("high_trust", 0.85, False)
    if auc >= 0.85:
        return ("med_trust", 0.90, False)
    if auc >= 0.70:
        return ("low_trust", 0.95, False)
    return ("untrusted", 0.95, True)  # consensus required


tiers = [threshold_for_class(c) for c in range(N_CLS)]
tier_counts = pd.Series([t[0] for t in tiers]).value_counts()
print(f"\n  Class tiers: {tier_counts.to_dict()}")

# Per-class cap based on tier
PER_CLASS_CAP = {
    "high_trust": 500,
    "med_trust": 300,
    "low_trust": 150,
    "untested": 80,
    "untrusted": 50,
}


# ---------- Filter & build pseudo-labels ----------
print("\nBuilding v2 pseudo-labels...")
rows_out = []
per_class_kept = {}
for c_idx in range(N_CLS):
    tier, thresh, require_consensus = tiers[c_idx]
    bruce_col = P_bruce[:, c_idx]
    perch_col = P_perch_soft[:, c_idx]
    mask = (~np.isnan(bruce_col)) & (bruce_col >= thresh)
    if require_consensus:
        mask &= (~np.isnan(perch_col)) & (perch_col >= 0.5)
    qual_idxs = np.where(mask)[0]
    # Sort by Bruce probability descending
    qual_idxs = qual_idxs[np.argsort(bruce_col[qual_idxs])[::-1]]
    cap = PER_CLASS_CAP.get(tier, 100)
    qual_idxs = qual_idxs[:cap]
    per_class_kept[classes[c_idx]] = len(qual_idxs)
    for i in qual_idxs:
        rows_out.append({
            "row_id": meta["row_id"].iloc[i],
            "filename": meta["filename"].iloc[i],
            "site": meta["site"].iloc[i],
            "hour": meta["hour"].iloc[i],
            "year": meta["year"].iloc[i],
            "class": classes[c_idx],
            "bruce": float(bruce_col[i]),
            "perch_soft": float(perch_col[i]) if not np.isnan(perch_col[i]) else float("nan"),
            "calibration_tier": tier,
            "bruce_labeled_auc": float(bruce_per_class_auc[c_idx]) if not np.isnan(bruce_per_class_auc[c_idx]) else float("nan"),
            "threshold_used": thresh,
            "consensus_required": require_consensus,
        })


labels_v2 = pd.DataFrame(rows_out)
print(f"  Total pseudo-labels: {len(labels_v2)}")
print(f"  Unique files: {labels_v2['filename'].nunique()}")
print(f"  Unique classes: {labels_v2['class'].nunique()}")

# Per-tier breakdown
print(f"\n  Per-tier:")
print(labels_v2.groupby("calibration_tier").agg(
    n_labels=("row_id", "count"),
    n_files=("filename", "nunique"),
    n_classes=("class", "nunique"),
    mean_bruce=("bruce", "mean"),
).round(3).to_string())

# Bruce confidence distribution
print(f"\n  Bruce confidence distribution:")
print(labels_v2["bruce"].describe().round(4).to_string())

# Per-class top counts
print(f"\n  Per-class label counts (top 20):")
print(labels_v2.groupby("class").agg(
    n=("row_id", "count"),
    tier=("calibration_tier", "first"),
    mean_bruce=("bruce", "mean"),
).sort_values("n", ascending=False).head(20).to_string())

# Per-(site, hour) coverage of pseudo-labels
print(f"\n  Per-(site, hour) coverage (top 20):")
print(labels_v2.groupby(["site", "hour"]).size().sort_values(ascending=False).head(20).to_string())

labels_v2.to_parquet(f"{OUT}/pseudo_labels_v2.parquet", index=False)
print(f"\nSaved {OUT}/pseudo_labels_v2.parquet")


# ---------- Visualize per-tier coverage ----------
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

# Coverage by tier
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
ax = axes[0]
labels_v2["calibration_tier"].value_counts().plot.barh(ax=ax)
ax.set_xlabel("# pseudo-labels")
ax.set_title("Pseudo-labels by Bruce-AUC calibration tier")

ax = axes[1]
sites_in = sorted(labels_v2["site"].unique())
site_cnt = labels_v2.groupby("site").size().sort_values()
site_cnt.plot.barh(ax=ax)
ax.set_xlabel("# pseudo-labels")
ax.set_title("Pseudo-labels by site")
plt.tight_layout()
plt.savefig(f"{OUT}/pseudo_v2_coverage.png", dpi=110)
plt.close()
print(f"Saved {OUT}/pseudo_v2_coverage.png")


# ---------- Compare v1 vs v2 ----------
v1 = pd.read_parquet(f"{OUT}/pseudo_labels.parquet")
print(f"\n=== v1 vs v2 ===")
print(f"  v1 rows: {len(v1)} | v2 rows: {len(labels_v2)}")
print(f"  v1 files: {v1['filename'].nunique()} | v2 files: {labels_v2['filename'].nunique()}")
print(f"  v1 classes: {v1['class'].nunique()} | v2 classes: {labels_v2['class'].nunique()}")
